# Generated by Django 4.1.4 on 2023-05-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="surname",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Отчество"
            ),
        ),
    ]
