# Generated by Django 4.1.4 on 2023-05-16 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_employees_management_employees_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер кабинета')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж (не обязательно)')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название кабинета (не обязательно)')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.employees', verbose_name='Закрепленный педагог(не обязательно)')),
            ],
        ),
    ]
