# Generated by Django 4.1.4 on 2023-05-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_cabinet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabinet',
            options={'verbose_name': 'Кабинет', 'verbose_name_plural': 'Кабинеты'},
        ),
    ]
