# Generated by Django 4.1.4 on 2023-05-17 06:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0009_classes_items_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employees",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="employees",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="employees",
            name="surname",
        ),
    ]
