# Generated by Django 4.1.4 on 2023-05-17 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0003_academicsubjects_alter_positions_options_and_more"),
        ("school", "0010_remove_employees_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="placework",
            name="school",
        ),
        migrations.AddField(
            model_name="placework",
            name="school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="settings.schools",
                verbose_name="Школа",
            ),
            preserve_default=False,
        ),
    ]
