# Generated by Django 4.1.4 on 2023-05-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0011_remove_placework_school_placework_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="employees",
            name="is_administrator",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Администратор?"
            ),
        ),
    ]
