# Generated by Django 4.1.4 on 2023-05-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_positions_alter_schools_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Учебные предметы',
            },
        ),
        migrations.AlterModelOptions(
            name='positions',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='schools',
            options={'verbose_name': 'Школа', 'verbose_name_plural': 'Школы'},
        ),
    ]
