# Generated by Django 4.1.4 on 2023-05-19 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Меню партнер",
                "verbose_name_plural": "Меню партнеры",
            },
        ),
        migrations.CreateModel(
            name="PartnersItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Название")),
                ("link", models.CharField(max_length=100, verbose_name="Ссылка")),
                ("is_active", models.BooleanField(verbose_name="Активный?")),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_menu.partners",
                        verbose_name="Партнер",
                    ),
                ),
            ],
        ),
    ]
