# Generated by Django 4.1.4 on 2023-05-19 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0003_academicsubjects_alter_positions_options_and_more"),
        ("school_menu", "0002_partners_is_active_partners_school_partners_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Названия пункта выподающего меню",
                        max_length=50,
                        verbose_name="Название пункта меню",
                    ),
                ),
                ("is_active", models.BooleanField(verbose_name="Активный?")),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="settings.schools",
                        verbose_name="Школа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Меню партнер",
                "verbose_name_plural": "Меню партнеры",
            },
        ),
        migrations.CreateModel(
            name="SitesItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Название")),
                ("link", models.CharField(max_length=100, verbose_name="Ссылка")),
                ("is_active", models.BooleanField(verbose_name="Активный?")),
                (
                    "sites",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_menu.sites",
                        verbose_name="Cайты",
                    ),
                ),
            ],
        ),
    ]
