# Generated by Django 4.1.4 on 2023-05-19 11:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school_menu", "0003_sites_sitesitems"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sites",
            options={"verbose_name": "Меню cайты", "verbose_name_plural": "Меню сайты"},
        ),
    ]
