# Generated by Django 4.1.4 on 2023-05-19 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school_menu", "0004_alter_sites_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partnersitems",
            name="partner",
        ),
        migrations.RemoveField(
            model_name="sites",
            name="school",
        ),
        migrations.RemoveField(
            model_name="sitesitems",
            name="sites",
        ),
        migrations.DeleteModel(
            name="Partners",
        ),
        migrations.DeleteModel(
            name="PartnersItems",
        ),
        migrations.DeleteModel(
            name="Sites",
        ),
        migrations.DeleteModel(
            name="SitesItems",
        ),
    ]
