# Generated by Django 4.1.4 on 2023-05-19 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("settings", "0003_academicsubjects_alter_positions_options_and_more"),
        (
            "school_menu",
            "0005_remove_partnersitems_partner_remove_sites_school_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Названия пункта выподающего меню",
                        max_length=50,
                        verbose_name="Название пункта меню",
                    ),
                ),
                ("is_active", models.BooleanField(verbose_name="Активный?")),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="settings.schools",
                        verbose_name="Школа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Меню шапки сайта",
                "verbose_name_plural": "Меню шапки сайта",
            },
        ),
        migrations.CreateModel(
            name="MenuItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Название")),
                ("link", models.CharField(max_length=100, verbose_name="Ссылка")),
                ("is_active", models.BooleanField(verbose_name="Активный?")),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_menu.menu",
                        verbose_name="Партнер",
                    ),
                ),
            ],
        ),
    ]
