# Generated by Django 4.1.4 on 2023-05-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_menu", "0006_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitems",
            name="new_tab",
            field=models.BooleanField(
                default=True, verbose_name="Открывать в новой вкладке?"
            ),
            preserve_default=False,
        ),
    ]
