# Generated by Django 4.1.4 on 2023-05-19 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school_menu", "0007_menuitems_new_tab"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitems",
            old_name="new_tab",
            new_name="is_new_tab",
        ),
    ]
